const HotelData = [
  {
    url1: require("../../Assets/Baris Stay/Pic1.webp"),
    url2: require("../../Assets/Baris Stay/Pic2.webp"),
    url3: require("../../Assets/Baris Stay/Pic3.webp"),
    url4: require("../../Assets/Baris Stay/Pic4.webp"),
    url5: require("../../Assets/Baris Stay/Pic5.webp"),
    url6: require("../../Assets/Baris Stay/Pic6.webp"),
    url7: require("../../Assets/Baris Stay/Pic7.webp"),
    url8: require("../../Assets/Baris Stay/Pic8.webp"),
    url9: require("../../Assets/Baris Stay/Pic9.webp"),
    Name: "Baris Stay",
  },
  {
    url1: require("../../Assets/Hotel Driver Stay Mus/Concept (8).jpg"),
    url2: require("../../Assets/Hotel Driver Stay Mus/Parking Area (1).jpg"),
    url3: require("../../Assets/Hotel Driver Stay Mus/Roof Top Cafe & Bar (3).jpg"),
    url4: require("../../Assets/Hotel Driver Stay Mus/Room 1 (4).jpg"),
    url5: require("../../Assets/Hotel Driver Stay Mus/Room 3 (2).jpg"),
    url6: require("../../Assets/Hotel Driver Stay Mus/Room 4 (4).jpg"),
    url7: require("../../Assets/Hotel Driver Stay Mus/Room 5 (2).jpg"),
    url8: require("../../Assets/Hotel Driver Stay Mus/Room 5 (3).jpg"),
    url9: require("../../Assets/Hotel Driver Stay Mus/Room 6 (1).jpg"),
    Name: "Driver Stay",
  },
  {
    url1: require("../../Assets/River Side Stay/Pic1.jpg"),
    url2: require("../../Assets/River Side Stay/Pic2.jpg"),
    url3: require("../../Assets/River Side Stay/Pic3.jpg"),
    url4: require("../../Assets/River Side Stay/Pic4.jpg"),
    url5: require("../../Assets/River Side Stay/Pic5.jpg"),
    url6: require("../../Assets/River Side Stay/Pic6.jpg"),
    url7: require("../../Assets/River Side Stay/Pic7.jpg"),
    url8: require("../../Assets/River Side Stay/Pic8.jpg"),
    url9: require("../../Assets/River Side Stay/Pic9.jpg"),
    Name: "River Side Stay",
  },
  {
    url1: require("../../Assets/The Pride/EXE WASHROOM 2-min - Copy (2).jpg"),
    url2: require("../../Assets/The Pride/LAWN 4-min - Copy (2).jpg"),
    url3: require("../../Assets/The Pride/LAWN DAY 1-min - Copy.jpg"),
    url4: require("../../Assets/The Pride/LAWN NIGHT new - Copy.jpg"),
    url5: require("../../Assets/The Pride/ROYAL ROOM 1-min.jpg"),
    url6: require("../../Assets/The Pride/chimney  new - Copy (2).jpg"),
    url7: require("../../Assets/The Pride/coridoor new - Copy.jpg"),
    url8: require("../../Assets/The Pride/drone - Copy.png"),
    url9: require("../../Assets/The Pride/regal 3-min.jpg"),
    Name: "The Pride",
  },
  {
    url1: require("../../Assets/The latitude Luxry Hotel/Pic1.JPG"),
    url2: require("../../Assets/The latitude Luxry Hotel/Pic2.JPG"),
    url3: require("../../Assets/The latitude Luxry Hotel/Pic3.JPG"),
    url4: require("../../Assets/The latitude Luxry Hotel/Pic4.JPG"),
    url5: require("../../Assets/The latitude Luxry Hotel/Pic5.JPG"),
    url6: require("../../Assets/The latitude Luxry Hotel/Pic6.JPG"),
    url7: require("../../Assets/The latitude Luxry Hotel/Pic7.JPG"),
    url8: require("../../Assets/The latitude Luxry Hotel/Pic8.JPG"),
    url9: require("../../Assets/The latitude Luxry Hotel/Pic9.JPG"),
    Name: "latitude Luxry",
    Description: "",
  },
];
export default HotelData;
